### ISSUE TITLE
Cannot find module 'lodash/fp/trim'

### ISSUE THREAD

**Issue by lnrd96** [qhuyduong/yabai-status-bar#2]
Hi all,

I cloned yabai-status-bar into my 'übersicht/widgets' folder as usual.
Instead of the status bar a white box with red text saying: 
> "Cannot find module 'lodash/fp/trim' from 'correctPath/yabai-status-bar/components'."

**Any tips** on how to get this running / find the problem would be **appreciated**.
Also suggestions for other bar-solutions for yabai would be welcome.

I'm running Mac OS 10.15.4 and Übersicht 1.4 (61) and Yabai 3.0.1.
[Screenshot from _Übersicht Debug Console Output_](https://imgur.com/qiHjF6W)

Thank you very much.

**Comment by qhuyduong** [comment]
@LeonardFish sorry for missing information. You have to run `yarn install` in that folder to install dependencies first.
